# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: openobserve
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.openObserve.service.type | default "ClusterIP" }}
  selector:
    app: openobserve
  ports:
  - name: http
    port: 5080
    targetPort: 5080
