# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: observability-tracing-opensearch
description: A Helm chart for OpenChoreo Observability Tracing module with OpenTelemetry Collector and OpenSearch
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - opensearch
  - observability
  - tracing
home: https://github.com/openchoreo/community-modules
maintainers:
  - name: OpenChoreo Team
dependencies:
  - name: opensearch
    alias: openSearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: 3.3.0
    condition: openSearch.enabled
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.140.0
    condition: opentelemetry-collector.enabled
