# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: opensearch-logs
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.openSearchSetup.openSearchPassword | quote }}
