# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: observability-metrics-prometheus
description: A Helm chart for OpenChoreo Observability Metrics module based on Prometheus
type: application
version: 0.2.1
appVersion: "0.2.1"
keywords:
  - prometheus
  - observability
  - metrics
home: https://github.com/openchoreo/community-modules
maintainers:
  - name: OpenChoreo Team
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 78.3.0
    condition: kube-prometheus-stack.enabled
