# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: observability-logs-opensearch
description: A Helm chart for OpenChoreo Observability Logs module with Fluent Bit and OpenSearch
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - opensearch
  - observability
  - logs
home: https://github.com/openchoreo/community-modules
maintainers:
  - name: OpenChoreo Team
dependencies:
  - name: opensearch
    alias: openSearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: 3.3.0
    condition: openSearch.enabled
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.54.0
    condition: fluent-bit.enabled
